POST http://localhost:5000/api/villas/admin/signup
Content-Type: application/json

{
    "email": "prince@gmail.com",
    "password": "prince"
}

###

POST http://localhost:5000/api/villas/guest/signup
Content-Type: application/json

{
    "fname": "wakesho",
    "lname": "wakesho",
    "email": "wakesho@gmail.com",
    "password": "wakesho"
}

###

POST http://localhost:5000/api/villas/signin
Content-Type: application/json

{
    "email": "prince@gmail.com",
    "password": "prince"
}

###

GET http://localhost:5000/api/villas/signin
Authorization: Bearer 
