POST http://localhost:5000/api/villas/admin/signup
Content-Type: application/json

{
    "email": "prince@gmail.com",
    "password": "prince"
}

###

POST http://localhost:5000/api/villas/guest/signup
Content-Type: application/json

{
    "fname": "wakesho",
    "lname": "wakesho",
    "email": "wakesho@gmail.com",
    "password": "wakesho"
}

###

POST http://localhost:5000/api/villas/signin
Content-Type: application/json

{
    "email": "prince@gmail.com",
    "password": "prince"
}

###

POST http://localhost:5000/api/villas/review
Content-Type: application/json


{
    "comment": "such a good place for the weekend",
    "rating": 5,
    "guest_id": 1,
    "property_id": 1,
    "date" : "12-01-2024"
}
